apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: aayushvijayvergiya/ticketing-app-orders-image
        # image: us.gcr.io/ticketing-dev-2309/orders
        env:
          - name: MONGO_URI
            value: 'mongodb://orders-mongo-srv:27017'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwtKey
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
  
---

apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
  - port: 4001
    targetPort: 4001
    name: orders
    protocol: TCP
