name: Tests-Orders

on:
  pull_request:
    paths:
      - 'auth/**'
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cd orders && npm install && npm run test:ci
